version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t jay:latest .
      - docker tag jay:latest 417656858312.dkr.ecr.us-west-2.amazonaws.com/jay:latest
  post_build:
    commands:
      - docker push 417656858312.dkr.ecr.us-west-2.amazonaws.com/jay:latest
      - printf '[{"name":jay-app,"imageUri":"%s"}]' 417656858312.dkr.ecr.us-west-2.amazonaws.com/jay:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
